### ISSUE TITLE
Can we setup without editable pip

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/hist#10]
Aghast uses [setup.py](https://github.com/scikit-hep/aghast/blob/master/python/setup.py) to setup environment for developers -- `python setup.py install`. Can we set up in the same way (we have setup.py too)? 

If we can, I think not to include `pip -e .` in dev-evironment.yml would be great.

**Comment by henryiii** [comment]
a) You should always use the pip command over the setup.py command if possible; pip patches in fixes in at times, and it can do things setup.py by itself can't, like install requirements if needed. There are a *few* commands that do still require setup.py directly, like `python setup.py sdist`, and that requires all requirements to be updated and installed beforehand, which is a pain.
b) `pip -e .` may support other tools like Flit one day, `setup.py anything` will never support any other tool
c) The point of having the `pip -e .` was to keep from having more commands for a user (install environment and then install editable package), but not sure if that is the best plan - but if not, you should still always recommend the correct `pip -e .`
d) Developers who use standard procedures should be able to setup any package without reading "how to setup" for every package
e) If you use mybinder or other tools, those expect/require standard procedures
f) I'll probably ask for Aghast to be updated to modern procedures soon - I'm writing up Scikit-HEP wide recommendations now
