### ISSUE TITLE
[BUG] README example fails

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/hist#110]
**Describe the bug**

When trying to run the [`README.md` Usage example](https://github.com/scikit-hep/hist/blob/4e31568a1e6ba849c253b0670aaea9f63ca98784/README.md#usage) for `hist` `v2.0.1` a 

```pytb
AttributeError: 'ConstructProxy' object has no attribute 'Variable'
```

is raised at histogram creation.

**To Reproduce**

```
$ python3 -m venv hist-bug-example
$ source hist-bug-example/bin/activate
(hist-bug-example) $ python -m pip install --quiet --upgrade pip setuptools wheel
(hist-bug-example) $ python -m pip install "hist[plot]"
(hist-bug-example) $ pip list
Package           Version
----------------- ---------
boost-histogram   0.11.1
certifi           2020.6.20
chardet           3.0.4
click             7.1.2
cycler            0.10.0
future            0.18.2
hist              2.0.1
histoprint        1.5.2
idna              2.10
kiwisolver        1.2.0
matplotlib        3.3.2
mplhep            0.2.2
numpy             1.19.2
packaging         20.4
Pillow            8.0.1
pip               20.2.4
pkg-resources     0.0.0
pyparsing         2.4.7
python-dateutil   2.8.1
requests          2.24.0
scipy             1.5.3
setuptools        50.3.2
six               1.15.0
typing-extensions 3.7.4.3
uncertainties     3.1.4
urllib3           1.25.11
wheel             0.35.1
(hist-bug-example) $ cat hist_readme_example_head.py 
from hist import Hist

# Quick construction, no other imports needed:
h = (
    Hist.new.Reg(10, 0, 1, name="x", label="x-axis")
    .Variable(range(10), name="y", label="y-axis")
    .Int64()
)
(hist-bug-example) $ python hist_readme_example_head.py 
Traceback (most recent call last):
  File "hist_readme_example_head.py", line 5, in <module>
    Hist.new.Reg(10, 0, 1, name="x", label="x-axis")
AttributeError: 'ConstructProxy' object has no attribute 'Variable'
```

**Expected behavior**

For the example to pass without errors.

**Comment by LovelyBuggies** [comment]
@matthewfeickert Thank you for reporting this bug. 

Try this:

```python
h = (
    Hist.new.Reg(10, 0, 1, name="x", label="x-axis")
    .Var(range(10), name="y", label="y-axis")
    .Int64()
)
```

Actually, the name should be "Var" not "Variable". I forgot to update this point in the README, I'm changing it now.

**Comment by matthewfeickert** [comment]
Thanks for fixing the `README` @LovelyBuggies. :+1: 

> it's not easy to sync dev and docs sometimes :-) btw

Agreed. In [`pyhf`](https://github.com/scikit-hep/pyhf/) we run `doctest` on our `README` examples to catch these things. Having `h.plot_pull(Callable)` makes that not possible as is (given the resulting `NameError`) but maybe something to look into?

**Comment by LovelyBuggies** [comment]
Callable means a user-defined func name here like pdf. You can refer to our docs/user guide/plot for more info.

**Comment by matthewfeickert** [comment]
> Callable means a user-defined func name here like pdf. You can refer to our docs/user guide/plot for more info.

Yes, I know what a callable is. I was pointing out that your current example will fail `doctest` as is given that the final line in it will not pass evaluation.
