### ISSUE TITLE
[FEATURE] storage string aliases

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/hist#114]
**Describe the feature you'd like**

I'm not sure if there are technical reason that would prevent this, but it would be nice if you could add string aliases for the storage options. So for example

```python
import hist
from hist import Hist

# Supported
h1 = Hist.new.Reg(100, -10, 10, name="x").Double()
h2 = Hist(hist.axis.Regular(100, -10, 10, name="x"), storage=hist.storage.Double())
# Feature request
h3 = Hist(hist.axis.Regular(100, -10, 10, name="x"), storage="double")
```

would all create equivalent histograms.

**Comment by henryiii** [comment]
While doing this, we should make the `storage=` optional if a storage is passed (not a string). It's quite obvious that hist.storage.X is a storage already.
