### ISSUE TITLE
[FEATURE] Cumulative histogram

### ISSUE THREAD

**Issue by rtesse** [scikit-hep/hist#139]
Dear developers,

I would like to create a cumulative histogram based on a histogram created using Hist. Is it possible to do this? 

Here is a minimal example of what I would like to have:  
 
```
import numpy as np
import hist
dist = np.random.lognormal(0.0, 1.0, int(1e4))
h = hist.Hist.new.Reg(bins=1000, start=0, stop=4, name='energy', label='E').Double()
h.fill(energy=dist, weight=dist)
```

### How to create a cdf using hist ? Something like: 
`cumHist = h.cumhist() 
`

Best regards,

Robin.

**Comment by henryiii** [comment]
Could you do `np.cumsum(hist.values())`? Or would more be better?

**Comment by rtesse** [comment]
Yes, it works but I would like to use the plotting capabilities of the module. If I do 
`h.values = np.cumsum(h.values())`
I have a `SyntaxError: cannot assign to function call`
Is it possible to have a method that creates a cumulative histogram and plot it like a histogram e.g: 
```
ch = h.cumhist()
ch.plot()
```

**Comment by henryiii** [comment]
```python
h[...] = np.cumsum(h.values())
```

perhaps?

**Comment by henryiii** [comment]
I actually have a proposal in https://github.com/scikit-hep/boost-histogram/discussions/504 that would have made your syntax valid.

**Comment by rtesse** [comment]
It works 👍  Thanks a lot. I will follow the discussion on boost-histograms.
