### ISSUE TITLE
Should Every Axis Have Name?

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/hist#14]
https://github.com/scikit-hep/hist/blob/be2c8380793807966f1ab58c4e50962fae7e45f9/src/hist/_internal/axis.py#L5-L17

Should every axis be forced to have a name? I see you let `title` to be an arg (cannot be omitted). Hence that `name` should have the same status, it is should be indispensable, too. But in the unit tests, we are supposed to pass the test where axes have no names, e.g.

https://github.com/scikit-hep/hist/blob/be2c8380793807966f1ab58c4e50962fae7e45f9/tests/test_general.py#L5

and 

https://github.com/scikit-hep/hist/blob/be2c8380793807966f1ab58c4e50962fae7e45f9/tests/test_named.py#L6

P.S. The current practice, i.e., #13, is to modify the tests to enforce them to have names. An alternative plan is to make `title` and `name` both omissible, which might be subject to the issue of filling-by-name (this functionality should be thrown out for hist with anonymous axes).

**Comment by LovelyBuggies** [comment]
Fixed. The current logic is: `Hist()`'s axes could have names or not, but must have names when filling by names; `NamedHist()`'s axes must have names, and must have names when filling by names. But both of them can be filled without name kwargs, like `fill(x, y)` in axis index order.

**Comment by jpivarski** [comment]
I think the idea was that the name would be the expression computed for that axis, which is always something that exists.

However, I can imagine a histogram object that doesn't know how it's filled—that it is passed precomputed numbers from an external program (like ROOT's histograms, in fact, which don't know where the argument to `Fill` came from).

In that case, though, I think it would make sense for the name to be a string of the integer position of the axis, such as `"0"`, `"1"`, and `"2"`. There's a one-to-one relationship between unpadded integer strings and the integers they represent.

We could make both name and title optional, but that weakens the distinction between them. The name is supposed to be a lookup tag and the title is supposed to be human-readable text (and therefore always optional). Without a lookup tag, we can still find an axis by its position, which is why defaulting to integer strings makes sense.

**Comment by LovelyBuggies** [comment]
@jpivarski As Hist is to provide shortcuts for HEPer, I think our Hist should support this functionality:

```python
h = hist.Hist(hist.axis.Regular(50, -3, 3))
h.fill(np.random.randn(1_000))
```

, which is the simplest demo.  This will keep the largest compatibility of Boost-Histogram codebase. Do you think so, @jpivarski? In this situation, I think we don't need to go so far to add `name='0'` for the axis **internally**. 

Thus, I think the point is, **`Hist` objects don't need to have names, but `NamedHist` objects should have**. And for those who have names, we are expected to allow users to fill them flexibly, that is, they can either fill by name and fill in the index order (with no names).

**Comment by LovelyBuggies** [comment]
According to the thoughts above, the implementation details are:

- **NamedHist**: 
  - when initializing, judge whether its axes all have valid names, if not, raise an error;
  - when filling, judge whether it is provided with arg, i.e. `h.fill(x,y)`, if yes, fill it according to the index order, if not, fill by names.
- **Hist**:
  - feel free to initialize;
  - when filling, judge whether it is provided with arg, i.e. `h.fill(x,y)`, if yes, fill it according to the index order, if not, fill by names.

**Comment by LovelyBuggies** [comment]
Btw, the current test-general.py (tests for `Hist()`) does not have `name` options:

https://github.com/scikit-hep/hist/blob/be2c8380793807966f1ab58c4e50962fae7e45f9/tests/test_general.py#L4-L8

But, I do not fully agree that `NamedHist()` could be created without names.

https://github.com/scikit-hep/hist/blob/be2c8380793807966f1ab58c4e50962fae7e45f9/tests/test_named.py#L4-L7

I think it should be:

```diff
- h = NamedHist(axis.Regular(10, 0, 1, title="x") )
+ h = NamedHist(axis.Regular(10, 0, 1, name="x", title="t") )  # title is optional
```

**Comment by jpivarski** [comment]
> @jpivarski As the Hist package is to provide shortcuts for HEPers, I think our Hist should support this:
> 
> ```python
> h = hist.Hist(hist.axis.Regular(50, -3, 3))
> h.fill(np.random.randn(1_000))
> ```

Yes, in this case, the `h` knows nothing about the fact that its argument is `np.random.randn(1_000)` and therefore, it can't automatically generate a name.

If it doesn't break anything to make names optional (i.e. if the lookup is not broken), then go ahead. If you find bugs in which a histogram can't find one of its axes, it's probably because of this, because the names were assumed to be unique keys. In that case, `"0"`, `"1"`, `"2"`, etc. for the axis position would make sense.

**Comment by henryiii** [comment]
The example test will mix name and title a bit; titles are always optional, and names are only optional for Hist, and not NamedHist. Feel free to correct the test. An axis has `Optional[str]` for the type of the name; when you add it to a histogram the internal copy *probably* can be assigned `"0"`, `"1"`, etc. for that histogram.

Filling of named hist should not be possible by order. NamedHist completely hide the order from users. If a user wants to access or fill a histogram by order, they should use Hist. Internally we do. have an order, but for NamedHist, we hide it from the user.

**Comment by henryiii** [comment]
Note: NamedHist is something the Coffea team explicitly want. They want to force names everywhere, because it removes a whole class of user mistakes related to assuming an order or changing the order (for example, by summing over or picking from an axis).

**Comment by henryiii** [comment]
We may not want to autogenerate "0", "1", and such; for a hist, you can always use positional access (just like boost-histogram), so names are not required, and "0" can't be made a keyword in Python, so using it would be a headache (you'd have to make a dict then use `**`).

**Comment by LovelyBuggies** [comment]
Alright, force names everywhere for NamedHist :) 

Correct what I have done today, now construct and fill without "0", "1" ... representation, forbid fill in index order for NamedHist, and add some exception handling.

**Comment by jpivarski** [comment]
> We may not want to autogenerate "0", "1", and such; for a hist, you can always use positional access (just like boost-histogram), so names are not required, and "0" can't be made a keyword in Python, so using it would be a headache (you'd have to make a dict then use `**`).

Remember that Aghast was never meant to be a nice user interface. It's "middleware."

**Comment by LovelyBuggies** [comment]
@jpivarski Hello Jim, I just realized that the name must be a valid python identifier, so cannot be "0", "1", etc. (and "_a" and "__a" are not recommended either). But don't worry, I have overcome this problem :)

**Comment by jpivarski** [comment]
This is what @henryiii was referring to about having to pass names as a dict: `**{"0": ..., "1": ...}`. It's not impossible, but annoying. (Unless names appear in another, non-kwargs context that actually does make it impossible.)
