### ISSUE TITLE
[FEATURE] Add ratio plot support to API

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/hist#148]
As there is already the ability in `hist` to add a ratio plot to the bottom of the main plot, as seen in the [`.plot_pull()` API](https://hist.readthedocs.io/en/latest/user-guide/notebooks/Plots.html#Via-Plot-Pull) it would be great if the ratio plot functionality (which looks super nice and clean in the `plot_pull` examples btw :+1:) could be added to the public API. If people agree this would be useful I'd be willing to contribute a PR.

**Describe the problem, if any, that your feature request is related to**

I don't have a problem per say, but just would like this feature to exist so that I don't have to implement it in a library that is already using `hist`. https://github.com/matthewfeickert/heputils/issues/22

**Describe the feature you'd like**

I'd like to have the ratio plot functionality that exists already in the `plot_pull` API to be available through a public API that would be something like `.plot_ratio`.

**Describe alternatives, if any, you've considered**

None, as this would be up to the developers to decide if this is in scope or not.

**Comment by henryiii** [comment]
Sounds good. Plot_pull could call plot_ratio. Could be easier to upstream to mplhep too.

**Comment by matthewfeickert** [comment]
> Sounds good. Plot_pull could call plot_ratio. 

That makes sense to me

> Could be easier to upstream to mplhep too.

I'll let @henryiii and @andrzejnovak decide where would be the best place for a PR, but at the moment it seems that 

https://github.com/scikit-hep/hist/blob/3827e75fb2587877ca805b30751ab9a8888113de/src/hist/plot.py#L129

is still mostly implemented in `hist` so I'll start work there until someone tells me to pivot.

**Comment by andrzejnovak** [comment]
Ideally, it would exist as a standalone function in mplhep such that one could also use it manually or with uproot TH1s, but since I'm not the one writing it I should shush :D

**Comment by henryiii** [comment]
I'd start by refactoring Hist's function, then we can upstream it and then move to using the new version.
