### ISSUE TITLE
Drop support for Python 3.6

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/hist#154]
In the near future (couple of months?), Hist may drop support for Python 3.6, following NEP 29 and the Scikit-HEP Python statement. If anyone needs 3.6 support, please comment here. Boost-histogram and UHI will likely follow Python EOL, so around December 2021, but Hist probably can follow NEP 29 and drop sooner.

**Comment by andrzejnovak** [comment]
`mplhep>=3` dropped 3.6 and `matplotlib<3.4`

**Comment by henryiii** [comment]
Next release of Hist likely will be the last 3.6 release.

**Comment by henryiii** [comment]
Done in #194.
