### ISSUE TITLE
[FEATURE] profile histograms

### ISSUE THREAD

**Issue by aminnj** [scikit-hep/hist#156]
I personally find myself constructing profiles (`TH2::ProfileX()/TH2::ProfileY()`) during exploratory analysis. Is this something best left to the user, or would `hist` benefit from having the ability to do something like `h.profile(0).plot()`? To consider a specific case of 2 numerical axes,

```python
import numpy as np

def calculate_profile(self, axis=0):
    # matches the default error option for `TH2::ProfileX/Y()`
    values = self.values()
    variances = self.variances()
    centers = self.axes[axis].centers
    if axis == 0:
        num = np.matmul(values, centers)
        num_err = np.sqrt(np.matmul(variances, centers ** 2))
    else:
        num = np.matmul(values.T, centers)
        num_err = np.sqrt(np.matmul(variances.T, centers ** 2))
    den = np.sum(values.T, axis=axis)
    den_err = np.sqrt(np.sum(variances.T, axis=axis))
    new_values = num / den
    new_variances = ((num_err / den) ** 2 - (den_err * num / den ** 2.0) ** 2.0)
    return new_values, new_variances
```
(apologies for the convoluted numpy operations. I'm sure it can be simplified with some more thought)
and
```python
import hist

np.random.seed(42)
xy = np.random.multivariate_normal([0, 1], cov=[[1.,0.8],[0.8,1]], size=1000)
h = hist.Hist(hist.axis.Regular(50, -3, 3),hist.axis.Regular(50, -3, 3)).fill(*xy.T)

fig, ax = plt.subplots()
h.plot()

profile_axis = 0
values, variances = calculate_profile(h, axis=profile_axis)
ax.errorbar(h.axes[profile_axis].centers, values, yerr=variances**0.5, marker=".", color="r", alpha=0.5)
```
would yield
![image](https://user-images.githubusercontent.com/5760027/111580825-72178700-8775-11eb-9b2f-92620bf3e38d.png)

**Comment by eduardo-rodrigues** [comment]
Great idea @aminnj! I'm also a big fan and user of profile plots. They are terrific when "poking" the data and for figuring out trends, tails in the projections on certain axes (variables), you name it. A big +1 from me on the idea.

**Comment by henryiii** [comment]
This is a Mean / WeightedMean storage histogram, right? Though making a Profile from an existing histogram would be new.

**Comment by henryiii** [comment]
We also need to work on better plotting support for Profiles, the information is present in the PlottableHistogram Protocol (`h.kind` returns `"MEAN"`), but I don't think we do much with it yet, like customize the plot.

**Comment by henryiii** [comment]
`h.profile(axis: str | int) -> Histogram[Mean | WeightedMean]` (pretending we had Generic histograms in the typing there, which we don't yet) would be nice, I think; you could give an int axis number or a string axis name, just like project.

**Comment by henryiii** [comment]
Simplification:

```python
num = np.matmul(values, centers)
# Can be written with the matmul operator:
num = values @ centers
# But, better yet, use tensordot explicitly and remove the silly .T stuff:
num = np.tensordot(values, centers, [[axis], [0]])
```

I would like to flip the definition of axis, I'd like to list the axis to profile over, rather than the "remaining" axis, because that generalizes far better to ND. (I think I've used that in my tensordot definition already; it also removes a lot of `.T`'s above).
