### ISSUE TITLE
[BUG] Plot artifact in baseline test images

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/hist#167]
**Describe the bug**

This was found while making test images for PR #161 

The baseline test image for pull plots that was introduced in PR #149 has an axis artifact that is viewable in the pull plot on the sides (it additionally suffers from axis problems from being plotted on subplots).

[![test_image_plot_pull.png](https://raw.githubusercontent.com/scikit-hep/hist/84a5d80e54ede36b9268e97b0fb545ca68f18957/tests/baseline/test_image_plot_pull.png)](https://github.com/scikit-hep/hist/blob/84a5d80e54ede36b9268e97b0fb545ca68f18957/tests/baseline/test_image_plot_pull.png)

**Steps to reproduce**

```
$ pip list | grep hist
boost-histogram               1.0.0
hist                          2.2.1
histoprint                    2.0.0
```

The following example is trying to replicate most of 

https://github.com/scikit-hep/hist/blob/e12f7485f823931ab1298a0ce2ee55f78b0add4d/tests/test_plot.py#L604-L625

```python
# example.py
import matplotlib.pyplot as plt
import numpy as np

from hist import Hist, axis


def pdf(x, a=1 / np.sqrt(2 * np.pi), x0=0, sigma=1, offset=0):
    return a * np.exp(-((x - x0) ** 2) / (2 * sigma ** 2)) + offset


if __name__ == "__main__":
    np.random.seed(42)

    hist_1 = Hist(
        axis.Regular(
            50, -4, 4, name="S", label="s [units]", underflow=False, overflow=False
        )
    ).fill(np.random.normal(size=1000))
    hist_2 = Hist(
        axis.Regular(
            50, -5, 5, name="S", label="s [units]", underflow=False, overflow=False
        )
    ).fill(np.random.normal(size=10000))

    fig = plt.figure(figsize=(10, 8))
    main_ax, pull_ax = hist_1.plot_pull(pdf)
    fig.savefig("debug_hist_1.png")

    fig = plt.figure(figsize=(10, 8))
    main_ax, pull_ax = hist_2.plot_pull(pdf)
    fig.savefig("debug_hist_2.png")
```

| `debug_hist_1.png` | `debug_hist_2.png` |
| -- | -- |
| ![debug_hist_1](https://user-images.githubusercontent.com/5142394/112225985-94892480-8bfb-11eb-889e-47105f3f3101.png) | ![debug_hist_2](https://user-images.githubusercontent.com/5142394/112226003-99e66f00-8bfb-11eb-9f97-60254135e84a.png) |

It can be seen that `debug_hist_2.png` (range: `[-5, 5]`) doesn't exhibit the behavior though `debug_hist_1.png` (range: `[-4, 4]`) does, and if you run with a range of `[-6, 6]` it will exhibit the behavior as well.

From the reproduced bug below I think this is due to the axis from the main axis being drawn over but the edges of it sticking out. I'm not sure though, and would defer to someone more expert in `matplotlib`. If you look at the artifact closely it appears to be the right hand side of the range limits (in this case `4` &mdash; it is easier to see with a range of `6`).

**Comment by matthewfeickert** [comment]
@andrzejnovak have you ever come across things like this before?

**Comment by andrzejnovak** [comment]
Heh that's new. I wonder if it's related to how the subplots are created https://github.com/scikit-hep/hist/blob/e12f7485f823931ab1298a0ce2ee55f78b0add4d/src/hist/plot.py#L251

I tend to use `plt.subplots()` so I am not sure if that could affect anything

**Comment by henryiii** [comment]
The `add_gridspec` is used because the figure might already exist. This line is missing:

```python
plt.setp(ax2.get_xticklabels(), visible=False)
```

The histogram line style needs to be improved, too, while I'm at it, I think.

**Comment by andrzejnovak** [comment]
Ah right, in which case it should use axis locators. Like cbars in mplhep. 

I see you've already made another fix, so I'm gonna leave that to adding pull to mplhep

**Comment by matthewfeickert** [comment]
> I see you've already made another fix, so I'm gonna leave that to adding pull to mplhep

Yeah I wasn't trying to say that it was a `mplhep` problem or anything, just that I was curious if you had seen this behavior in the past. :+1:
