### ISSUE TITLE
[FEATURE] Typing Hints for `get_item` and `set_item`

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/hist#17]
**Describe the problem, if any, that your feature request is related to**

Don't know how to add typing hints for these two func.

https://github.com/scikit-hep/hist/blob/dc9b209dfa5d2fa934a803c9cb589b414314fc13/src/hist/named.py#L50

https://github.com/scikit-hep/hist/blob/dc9b209dfa5d2fa934a803c9cb589b414314fc13/src/hist/named.py#L66

**Comment by LovelyBuggies** [comment]
And the typing hints of `fig` and `ax` for 

https://github.com/scikit-hep/hist/blob/ef9e638f24ecd727beb8540e0afe792241335322/src/hist/general.py#L9

**Comment by henryiii** [comment]
`fig` and `ax` are easy; you can use `Optional[matplotlib.figure.Figure]` and `Optional[matplotlib.axes._subplots.AxesSubplot]` - if matplotlib doesn't have type hints yet, these will not be much more helpful than `Optional[Any]`, but they will be useful if/when it does.

get/set item are going to be harder. We should make type aliases for them, but that just moves the problem. They will be a `Tuple[Union[X], ...]` of items, but we need `X`. Maybe `Callable, str, int`?

**Comment by LovelyBuggies** [comment]
MPL doesn't have typing hints yet. Now I have typing hints for function `pull_plot` like this:

```python
def pull_plot(
        self,
        func: Callable,
        fig: Optional[matplotlib.figure.Figure] = None,
        ax: Optional[matplotlib.axes._subplots.AxesSubplot] = None,
        pull_ax: Optional[matplotlib.axes._subplots.AxesSubplot] = None,
        **kwargs,
    ) -> Union[
        Optional[matplotlib.figure.Figure],
        Optional[matplotlib.axes._subplots.AxesSubplot],
        Optional[matplotlib.axes._subplots.AxesSubplot],
    ]:
```
It says 

```bash
$ pre-commit run --all-files
black....................................................................Passed
Check for added large files..............................................Passed
Mixed line ending........................................................Passed
Trim Trailing Whitespace.................................................Passed
Check for merge conflicts................................................Passed
Check for case conflicts.................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Check Yaml...............................................................Passed
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

src/hist/general.py:70: error: Item "None" of "Optional[Any]" has no attribute
"add_gridspec"
                grid = fig.add_gridspec(4, 4, wspace=0.5, hspace=0.5)
                       ^
src/hist/general.py:73: error: Item "None" of "Optional[Any]" has no attribute
"add_subplot"
                ax = fig.add_subplot(grid[0:3, :])
                     ^
src/hist/general.py:78: error: Item "None" of "Optional[Any]" has no attribute
"add_subplot"
                pull_ax = fig.add_subplot(grid[3, :], sharex=ax)
```

Btw, am I using the right typing manner for the returns, I tried:

```python
def pull_plot(
        self,
        func: Callable,
        fig: Optional[matplotlib.figure.Figure] = None,
        ax: Optional[matplotlib.axes._subplots.AxesSubplot] = None,
        pull_ax: Optional[matplotlib.axes._subplots.AxesSubplot] = None,
        **kwargs,
    ) -> 
        Optional[matplotlib.figure.Figure],
        Optional[matplotlib.axes._subplots.AxesSubplot],
        Optional[matplotlib.axes._subplots.AxesSubplot]
    :
```

But pre-commit says it cannot reformat.

```bash
$ pre-commit run --all-files
black....................................................................Failed
- hook id: black
- exit code: 123

error: cannot format /Users/nino/Documents/GitHub/hist/src/hist/general.py: Cannot parse: 35:9:     ) -> 
Oh no! 💥 💔 💥
10 files left unchanged, 1 file failed to reformat.

Check for added large files..............................................Passed
Mixed line ending........................................................Passed
```

**Comment by LovelyBuggies** [comment]
> get/set item are going to be harder. We should make type aliases for them, but that just moves the problem. They will be a `Tuple[Union[X], ...]` of items, but we need `X`. Maybe `Callable, str, int`?

Yeah, it should include many possibilities, let me work on the `Hist` first and back to it in the next week :)

**Comment by henryiii** [comment]
> error: Item "None" of "Optional[Any]" has no attribute

Nice, even with no type hints in mpl, MyPy found a bug! You need to support a user passing "None" here; you should do something like:

```python
if ax is None:
    ax = ...
```

(fill in the ...).

**Comment by henryiii** [comment]
To return a tuple, you need to write
```python
     -> 
        Tuple[
            Optional[matplotlib.figure.Figure],
            Optional[matplotlib.axes._subplots.AxesSubplot],
            Optional[matplotlib.axes._subplots.AxesSubplot],
    ]:
```

(Black will make it prettier)

**Comment by LovelyBuggies** [comment]
> > error: Item "None" of "Optional[Any]" has no attribute
> 
> Nice, even with no type hints in mpl, MyPy found a bug! You need to support a user passing "None" here; you should do something like:
> 
> ```python
> if ax is None:
>     ax = ...
> ```
> 
> (fill in the ...).

Actually, I have.

```python
if fig == None:
            fig = plt.figure(figsize=(8, 8))
            grid = fig.add_gridspec(4, 4, wspace=0.5, hspace=0.5)
        else:
            grid = fig.add_gridspec(4, 4, wspace=0.5, hspace=0.5)

        if ax == None:
            ax = fig.add_subplot(grid[0:3, :])
        else:
            pass

        if pull_ax == None:
            pull_ax = fig.add_subplot(grid[3, :], sharex=ax)
        else:
            pass
```

**Comment by henryiii** [comment]
You need to use `is` With None, not ==. == does not have to be defined on all classes, and so could error.

**Comment by LovelyBuggies** [comment]
Thx, it works. Nice to see mypy found my bugs!

**Comment by henryiii** [comment]
Done. :)
