### ISSUE TITLE
[DOCS] Revise plot_ratio and plot_pulll docs examples in Plots notebook

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/hist#188]
## How do you want to improve the docs

There's a few things in the existing docs example notebooks that aren't correct. For example, the original `plot_pull` example has the following line

```python
ax, pull_ax = hh.plot_pull(
    pdf,
    eb_ecolor="steelblue",
    eb_mfc="steelblue",
    eb_mec="steelblue",
    eb_fmt="o",
    eb_ms=6,
    eb_capsize=1,
    eb_capthick=2,
    eb_alpha=0.8,
    fp_c="hotpink",
    fp_ls="-",
    fp_lw=2,
    fp_alpha=0.8,
    bar_fc="royalblue",
    pp_num=3,
    pp_fc="royalblue",
    pp_alpha=0.618,
    pp_ec=None,
    ub_alpha=0.2,
)
```

which is no longer correct, as `plot_pull` and `plot_ratio` return artist tuples now and not axes. The `plot_pull` example in the Plot Ratio examples could probably just be moved up and then the `plot_ratio` examples could have objects assigned to the returns so the artist tuples aren't printed out in the notebook. So something like

```python
fig = plt.figure(figsize=(10, 8))
artists = hist_1.plot_ratio(
    hist_2,
    rp_ylabel=r"Ratio",
    rp_num_label="hist1",
    rp_denom_label="hist2",
    rp_uncert_draw_type="bar",
);
```

## Where is the typos and defects

https://github.com/scikit-hep/hist/blob/7e8c76187899dff659d97e1eef3a9469b4966a8b/docs/user-guide/notebooks/Plots.ipynb

## What contents do you expect

Revisions as oultined above.

**Comment by henryiii** [comment]
Sounds good to me. Docs do need some work, I just recently fixed them so they are stored unevaluated and run on RtD; this caught and fixed a few issues. We got unlucky on the tuple unpacking for the artists, I expect.
