### ISSUE TITLE
[FEATURE] Add "efficiency" option to `.plot_ratio` kwarg `rp_uncertainty_type`

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/hist#195]
**Describe the problem, if any, that your feature request is related to**

Given [this question on Gitter](https://gitter.im/HSF/PyHEP-histogramming?at=607700c955d78266a6448ae2) from @heatherrussell it probably isn't very clear how to create a ratio plot where the ratio shown is an efficiency from both the API and the User Guide example that I've added.

**Describe the feature you'd like**

What might help is if in addition to 

https://github.com/scikit-hep/hist/blob/f3e9b74fcb0dd5ff757292491d2829910127fe13/src/hist/intervals.py#L114

there was an "efficiency" option that would be used as an alternative to "poisson-ratio"

https://github.com/scikit-hep/hist/blob/f3e9b74fcb0dd5ff757292491d2829910127fe13/src/hist/intervals.py#L138-L140

An example should also be added to the User Guide.

**Describe alternatives, if any, you've considered**

Not adding an alternative option but making only a more clear example of how to make an efficiency ratio plot in the User Guide.

**Comment by cranmer** [comment]
👍 FYI: @eweik is looking for this.

**Comment by matthewfeickert** [comment]
>  FYI: @eweik is looking for this.

Cool. @eweik if you start on this before I circle back to this can you please open a draft PR as soon as you get going (to make it clear this is being worked on and I should just help with the review)?
