### ISSUE TITLE
[BUG] Contrary to docstring, axis name has no setter

### ISSUE THREAD

**Issue by meliache** [scikit-hep/hist#225]
**Describe the bug**

Can't directly set the `name` of an already created hist axis, even though the docstring [suggests](https://github.com/scikit-hep/hist/blob/d78d97618b92d72877144e8c1836e03eca8cf4cf/src/hist/axis/__init__.py#L60) that the property is also a setter.
``` python
    @property
    def name(self: AxisProtocol) -> str:
        """
        Get or set the name for the Regular axis
        """
        return self._ax.metadata.get("name", "")
```
I suggest either adding a setter function (similar to what was done for the `label` property) or adapt the docstring.

**Steps to reproduce**
In hist version `2.3.0`:

``` python
a = hist.axis.Regular(10, 0, 10, name="a")
a.name = "b"  # AttributeError: can't set attribute
```

**Comment by henryiii** [comment]
That's a mistake in the docstring. Names are not settable since that could invalidate a histogram (you could set two axes to the same name and it can't be validated).

Thanks, needs clarification.
