### ISSUE TITLE
[FEATURE] Update Numpy 1.20 to 1.21 for mypy

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/hist#245]
We have added types to ndarray, which requires NumPy 1.21 support. We are supposed to make this update for mypy entry in the pre-commit-config.

Probably will hit boost-histogram, too.

**Comment by henryiii** [comment]
We need:

* `np.ndarray` -> `np.typing.NDArray[Any]` (or use the actual DType here)
* Add strings around the expressions in boost-histogram (Hist is okay)
* Bump the version to 1.21 in pre-commit

**Comment by amangoel185** [comment]
Fix completed for `boost-histogram` too with [#625](https://github.com/scikit-hep/boost-histogram/pull/625) in [Boost-histogram](https://github.com/scikit-hep/boost-histogram).
