### ISSUE TITLE
[DOCS] Need More Instructions on Quick constructs

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/hist#251]
I find it very confusing when switching between the quick/regular hist construction or looking things up in docs. If the full names were also usable it would help. 

I am afraid this is the consequence of "There should be one-- and preferably only one --obvious way to do it."

**Comment by LovelyBuggies** [comment]
I had a discussion with Henry about this once. He argues that we are expected to distinguish the quick construction in Hist from the regular construction methods in BH. So when you want to quick construct histograms, you can use abbr of axis types, i.e., Hist.new.Reg, Hist.new.Bool, Hist.new.Var, Hist.new.Int, Hist.new.IntCat, Hist.new.StrCat.

Yes, I just took a look at the documentation and there is a lack of index and description for quick construction methods, we will update this immediately. In addition, we acknowledge that the docs are asynchronous a bit from our development for now. Aman and I will be working on the docs update soon.

**Comment by andrzejnovak** [comment]
It might be a docs issue only and I am a fan of shortcuts, but I did not find them especially intuitive and it's frustrating to find things being implemented "differently" between `hist` and `bh`. I don't really see any drawbacks to the quick proxy taking full axis names as well tbh.

**Comment by henryiii** [comment]
It's actually less important now that we added "new"; originally, we would have had `Hist.Regular` which would have been very visible, and very easy to confuse with `hist.axis.Regular`, which it clearly was not - `Hist(Hist.Regular(10,0,1))` would have been a pretty easy error. Also, I'm now wondering if we could make a Hist proxy with a single axis actually work as an axis if someone did make that mistake.

**Comment by LovelyBuggies** [comment]
I think this has been solved. Thanks, henry!
