### ISSUE TITLE
Followup for Stacks

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/hist#254]
After the initial feature ships post #169, these are some things that we should do (I had several I can't remember at the moment):

* [x] Support showing _histogram_ titles in the legend.
* [ ] Add typing support for titles
* [x] Support Stack.axes as long as we are sure we always will have matching axes (I think we will)
* [x] Add `histoprint` support to `Stack` 

I think `.stack(axis)` will be popular enough that it really doesn't matter if we don't add the `|` shortcut I originally proposed. But we can add that if it seems to be needed.

**Comment by henryiii** [comment]
@andrzejnovak might not agree but I'd be really tempted to retire the `hist_2d.plot()` magic shortcut when one is a category now that `hist_2d.stack(axis).plot()` exists and is much more explicit. Would also simplify the repr.

**Comment by andrzejnovak** [comment]
@henryiii got me, I am convinced the (Cat, Reg) use case is so common it deserves a shorthand even at the expense of explicitness
Worst case scenario there is: user wants a 2D plot, tries `.plot()`, that's not it, tries `.plot2d()`

Side note: I am no longer 100% on the repr needing to project to 1D in this case, maybe 60 now.

**Comment by LovelyBuggies** [comment]
Since we always have matching axes, can we just return the axes of the first histogram in the stack as `s.axes`?

```python
ax = axis.Regular(50, -5, 5, underflow=False, overflow=False, name="X")
h1 = Hist(ax).fill(2 * np.random.normal(size=500) + 2 * np.ones((500,)))
h2 = Hist(ax).fill(2 * np.random.normal(size=500) - 2 * np.ones((500,)))
h3 = Hist(ax).fill(np.random.normal(size=600))
s = Stack(h1, h2, h3)
s.axes # should be (Regular(50, -5, 5, underflow=False, overflow=False, name='X', label='X'))?
```
