### ISSUE TITLE
[FEATURE] bulk name setting for AxesTuple

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/hist#274]
We should allow the following:

```python
hist.axes.name = ("name1", "name2", ...)
```

Names are read-only so that invalid histograms can't be made, but we can validate in this case, since we know all the names. We should have the same warning if names overlap with fill arguments as when constructing.

**Comment by matthewfeickert** [comment]
Thanks @henryiii for opening this. @amangoel185 for context, this is coming up because of the [following question on Gitter](https://gitter.im/HSF/PyHEP-histogramming?at=60fd148972c37b6f45719883)

> Matthew: If you have a `hist.hist.Hist` object that someone else made and serialized to give to you, and upon deserializing realize that the `name` and `label` field for the axes has information that should have been put in `metadata` placed in them (e.g., `hist_1.axes[0].name` gives `wjets` instead of something like `pt`) is there a way to update the `name` and `label` in a copy of the histogram? `name` and `label` are read only in boost-histogram, so is there any way to get around this other then manually making new histogram objects and filling them with the old histogram contents?
>
> Henry: Well, `label` is easy, it's not read-only. Only name is, because we validate that it doesn't get duplicated inside a histogram. You can set it via a secret method (`hist_1.axes[0]._ax.metadata`, IIRC), but I've intended to allow it to be set in bulk, that is, `hist.axes.name = ("name1", "name2")`, as that we can validate. I'll open an issue for that.
