### ISSUE TITLE
Update to boost-histogram 0.8.0

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/hist#29]
We should update to boost-histogram 0.8.0. Things to watch for (that I currently recall):

* New Boolean axis type can now be used
* We can drop the workaround we had for `.project` (IIRC?)
* `bh.sum is sum` now
* `rank` should be changed to `ndim`, like NumPy (do a `git grep rank` from command line, or however you like to do it)

**Comment by LovelyBuggies** [comment]
> New Binary axis type can now be used

Should we drop the `Bool` axis in hist?

> We can drop the workaround we had for .project (IIRC?)

I don't think we can drop it, since hist's `project` allow projection via names.

> bh.sum is sum now

This won't cause changes in hist package, currently.

> rank -> ndim

I'll make a change correspondingly.

**Comment by henryiii** [comment]
> Should we drop the Bool axis in hist?

It should become a wrapper for Boolean and be called Boolean.

> I don't think we can drop it, since `hist`'s project allow projection via names.

I think the problem was we couldn't disable axes numbers in NamedHist without the fix?

**Comment by LovelyBuggies** [comment]
> It should become a wrapper for Boolean and be called Boolean.

Okay. I'll change them.

> I think the problem was we couldn't disable axes numbers in NamedHist without the fix?

First, we could disable axes numbers in NamedHist just by **rewriting** the `project` function (eliminate the axes number projection in `BaseHist` and the other remain the same). Second, I am not sure what is the corresponding PR in BH that fix it (only BH PR 185 in the new release has something to do with `project`, but it seems not to be related to this issue).

**Comment by henryiii** [comment]
PR 377.

**Comment by LovelyBuggies** [comment]
There might be a bug:

```python
import boost_histogram # -V 0.8.0

h = bh.Histogram(bh.axis.Boolean(), bh.axis.Boolean(), bh.axis.Boolean()).fill(
            [True, True, True, True, True, False, True],
            [False, True, True, False, False, True, False],
            [False, False, True, True, True, True, True],
        )

true_only = h[{2: bh.loc(True)}] # should work
```

I think this should work just like `Regular` axes and `h` should be reducible. But it does not.

```log
ValueError: axis 2 is not reducible
```
