### ISSUE TITLE
[FEATURE] .density

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/hist#30]
**Describe the problem, if any, that your feature request is related to**

We should have a one-item call for density,

**Describe the feature you'd like**

We should return either a NumPy array or a "Histogram" - the later would have nicer plotting tools, but it's not truly a "histogram", and filling really no longer really works. Should probably always be a double histogram. Might be best to have a Density subclass of Histogram.

This might be upstreamed to boost-histogram at some point.

**Comment by LovelyBuggies** [comment]
I wonder why we cannot just create a method named `h.density()` and return a new histogram object (double storage). Why "it's not truly a 'histogram'", and why "filling no longer works"?

**Comment by henryiii** [comment]
It doesn't have the same meaning. Once you've computed a density, it is no longer a collection of counts. It doesn't make sense to fill, as then it will no longer be a density either.

Ideally, Density would have axes and plots and indexing, but no fills. But it would be easier not to remove fill, as you can't delete a method via subclassing. And likely not worth the effort to use mixing everywhere.

**Comment by henryiii** [comment]
We can start by returning a Double histogram, though, and maybe that's enough.

**Comment by LovelyBuggies** [comment]
> We can start by returning a Double histogram, though, and maybe that's enough.

Okay. But if you really want a Double subclass, one way is to have `raise Exception(f"Density cannot be filled")` in `fill` function. But I am not sure whether it is in a good manner :)

**Comment by LovelyBuggies** [comment]
Maybe to create subclasses named "Density", "BaseDensity" and "NamedDensity" (children of Hist, BaseHist, NamedHist, respectively) is ok. But this topic is subjected to more discussion, so I just use `self/self.sum()` for convenience now.
