### ISSUE TITLE
[DOCS] hist variable name shadows library

### ISSUE THREAD

**Issue by jonas-eschle** [scikit-hep/hist#354]
In the quickstart, the created histograms is usually called `hist` as in
```
import hist

....

hist = Hist(...)
```
which is probably a bad idea as the library is also called hist and we therefore redefine the variable `hist`.

I would propose to rename it to `h`  (while I am not a huge fan of one letter variables, obviously, it may does it for this case?), but otherwise the more verbose `histogram` or `histo` (a bit too close to `hist` I think) would also do it.

Or what do you think?

**Comment by henryiii** [comment]
@all-contributors please add @jonas-eschle for docs

**Comment by jonas-eschle** [comment]
Solved in #355
