### ISSUE TITLE
AxesTuple

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/hist#36]
AxesTuple needs to be extended to support name-based access. We might need a change in boost-histogram to make sure we can override this class everywhere.

`h.axes["x"]` should be the axes with the name "x".

**Comment by LovelyBuggies** [comment]
> We might need a change in boost-histogram to make sure we can override this class everywhere.

Does boost-histogram support names for axes?

**Comment by henryiii** [comment]
No, it's a Hist feature, boost-histogram only has `.metadata`. That's why we need a hist subclass of `AxesTuple`, that adds name support.
