### ISSUE TITLE
[DOCS] Add citation metadata wtih CITATION.cff

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/hist#413]
## How do you want to improve the docs

If there is interest, it would be nice to add a [`CITATION.cff`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) especially as there is already a [Zenodo archive for `hist`](https://doi.org/10.5281/zenodo.4057112).

If this is of interest I would be happy to make the PR.

## Other Scikit-HEP projects with `CITATION.cff`

* https://github.com/scikit-hep/awkward/pull/1257
* https://github.com/scikit-hep/pyhf/pull/1551

**Comment by amangoel185** [comment]
I think that would be a good addition! We could potentially even make it a standard across all Scikit-HEP projects.

**Comment by matthewfeickert** [comment]
> We could potentially even make it a standard across all Scikit-HEP projects.

[This is a goal](https://gitter.im/Scikit-HEP/community?at=629e7ceb06a77e1e18737c63).

The question that has come up in Scikit-HEP and IRIS-HEP meetings would be how to establish the authors that get added. The idea is that this would be up to the project dev team and maintainers to decide but that it would probably be those two groups, as other contributors would get recognition from having their contributions lists and/or through `allcontributors`. 

So for `hist` I would think the authors would be: @henryiii, @LovelyBuggies, and @amangoel185. @henryiii Am I correct on that?
