### ISSUE TITLE
[BUG] Fails to build from a tarball: expects git to be present

### ISSUE THREAD

**Issue by yurivict** [scikit-hep/hist#436]
Error:
```
LookupError: Error getting the version from source `vcs`: setuptools-scm was unable to detect version for /disk-samsung/freebsd-ports/misc/py-hist/work-py39/hist-2.6.1-31-g9d6543a.
```

Package builders typically use tarballs, not git clones.

Could you please make this error non-fatal or add a way to supply the version by the caller?

**Comment by henryiii** [comment]
Set `SETUPTOOLS_SCM_PRETEND_VERSION` to the version and it won’t require git.

I think we can actually make the git archive work by itself as well now with setuptools_scm 7+.

**Comment by yurivict** [comment]
```SETUPTOOLS_SCM_PRETEND_VERSION``` helps, thanks.

**Comment by henryiii** [comment]
There should be a version setuptools_scm can use even in the tarball now.
