### ISSUE TITLE
[DOCS] Please add to docs how to run tests

### ISSUE THREAD

**Issue by yurivict** [scikit-hep/hist#442]
## How do you want to improve the docs

The [Installation section](https://hist.readthedocs.io/en/latest/user-guide/installation.html) doesn't explain how to run tests.
The standard pytest command doesn't find tests.

**Comment by amangoel185** [comment]
Hi @yurivict, the testing information is under the [Contributing](https://hist.readthedocs.io/en/latest/contributing.html) section rather than Installation!

`pytest` should work well in a development environment if you're in Hist's root directory.

**Comment by amangoel185** [comment]
Closing this issue since I believe it's resolved. @yurivict, feel free to follow up!
