### ISSUE TITLE
[FEATURE] .T shortcut for .project(1,0) of a 2D hist

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/hist#513]
I was trying to flip x/y axes of a 2d hist and was pointed to #133 after initially trying some guesswork. One of the things I reached for was  a `.T` method which incidentally is also mentioned in #133. Is that perhaps enough of a suggestion that this would be a good API shortcut to have?

**Comment by henryiii** [comment]
@fabriceMUKARAGE, could you do this? It would be something like this:

```python
@property
def T(self) -> Self:
    return self.project(*reversed(range(self.ndim)))
```

Plus a test or two.

**Comment by fabriceMUKARAGE** [comment]
@henryiii sure, noted! I am going to work on that.
