### ISSUE TITLE
Fix Hist and NamedHist

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/hist#58]
* Does named indexing work on all Hist's? I don’t see the code for it in BaseHist, only in NamedHist. Something like this: `h[{“x”:2}]` should be converted into `h[{0:2}]` assuming that axes 0 has name `"x"`. 
* NamedHist should simply verify that the index item is a dict, and that it has only string keys. Then it should just call BaseHist's indexing.
* NamedHist's fill should simply be: `def fill(self, **kwargs): return super().fill(**kwargs)` (maybe with a few more keyword arguments listed to be nice to the user's inspection tools). BaseHist should be able to fill via kwargs or via position.

Overall, NamedHist should be pretty short, it is just taking away functionally (position-based access) from BaseHist. I'm not sure how strict we want to be - we can also have an `OnlyNamedAxesTuple` too.

Also we should make sure you can cast between Hist and NamedHist. `Hist(NamedHist(...))`, etc. I can do that one.

**Comment by LovelyBuggies** [comment]
The origin concern is "NamedHist **extends** the general Hist". But looking from now, maybe you want to say "NamedHist is a child of general Hist, who only uses names". If so (general Hist covers all funcs of NamedHist), why not use NamedHist as the superclass of Hist?

**Comment by henryiii** [comment]
Because they all inherit from boost. Histogram only allows position access. Hist adds name access. NamedHist forces only name access.

Also, NamedHist is only a restriction for the uses (1 user?) who believes that you should never depend on the position of an axis, bit only the name. In a way, it's more of a demo (you can modify a Hist), than something that will be generally useful.

It's possible to restrict features in a child class, though you have to be careful and you can't remove methods (but we don't need to).

**Comment by LovelyBuggies** [comment]
So do I need to make that changes?

**Comment by henryiii** [comment]
Which change?

**Comment by LovelyBuggies** [comment]
Make string-key dict index available for Based and general Hist.

**Comment by henryiii** [comment]
Okay, good. 

This is why I said, about the docs:

NamedHist is probably mostly just a mention “oh, and if you want to force all axes to have names and names to always be used, use NamedHist.

We may end up allowing index based access in a few places in named hist. I want to see what the person who originally requested it is okay with. Not allowing integer based access to a `.axes` is likely to break a lot, like plotting. I think fill + indexing + projection is likely enough.
