### ISSUE TITLE
Name Constrains

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/hist#6]
@henryiii, I just realized that maybe we need to screen out some names like `name="x 1d"` or change them automatically to `name="x-1d"` (GitHub does this), could you provide some ideas concerning which kinds of names should be abandoned or revised?

**Comment by henryiii** [comment]
That is the distinction between "name" and "title" - name would be required to be a valid python identifier (and might also have to restrict "sample" and "weight"). Title can be anything, so someone who wants "x 1d" could make that the title, and that's what plotting tools would use.

**Comment by LovelyBuggies** [comment]
Ok, I will add this constrain.

**Comment by LovelyBuggies** [comment]
Solved by Nino-hist PR [#8](https://github.com/LovelyBuggies/Nino-hist/pull/8).
