### ISSUE TITLE
plot2D_full with different axes scale or binning

### ISSUE THREAD

**Issue by fmazzasc** [scikit-hep/hist#87]
Hello,
I am trying to use the useful plotting function: `plot2d_full()` . I am not able to properly display the plot when the scale or the binning of the x-axis are different with respect to the y-axis. Example:

```
a_1 = np.random.randn(1000)-3
a_2 = np.random.randn(1000)+3
h2 = hist.Hist(
    hist.axis.Regular(50, -5, -1, name="neg", underflow=False, overflow=False),
    hist.axis.Regular(50, 1, 5, name="pos", underflow=False, overflow=False)
)
h2.fill(a_1,a_2)
ax = h2.plot2d_full()
```
In this case the position of the x-Gaussian is shifted and the result doesn't look good. Moreover if I try to change the binning in one of the two axis I obtain the following error message:
`ValueError: x and y must have same first dimension, but have shapes (40,) and (50,)`

Am I missing something?

**Comment by LovelyBuggies** [comment]
Hi @fmazzasc , thanks for your feedback.

> In this case the position of the x-Gaussian is shifted and the result doesn't look good.

True it is, I have fixed it. Now you can get output like this for your code snippet:

![image](https://user-images.githubusercontent.com/29083689/92065377-349f6d80-edd2-11ea-9484-94cd75f1b4a2.png)

> Moreover if I try to change the binning in one of the two axis I obtain the following error

If I understand correctly, you want to rebin the axis. How did you rebin, could you offer a code snippet?

**Comment by fmazzasc** [comment]
Hi,
before your fix if you tried to change the number of bins in one of the two axes you would obtain the error specified above. Following the previous example this change reproduced the problem:
```
h2 = hist.Hist(
    hist.axis.Regular(50, -5, -1, name="neg", underflow=False, overflow=False),
    hist.axis.Regular(40, 1, 5, name="pos", underflow=False, overflow=False)
)
```
But now also this issue seems to be solved with your fix.
Thanks a lot!

**Comment by LovelyBuggies** [comment]
> But now also this issue seems to be solved with your fix.

Okay, thanks for reporting the bug!
